Profession/urls.py
from django.contrib import admin
from django.urls import path
from Test import views as test_views
from LoginSys import views as auth_views
from Pages import views as pages_views
from PersonalAccount import views as account_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  # Админка
    path('home/', pages_views.home_page),  # Стартовая страница
    path('account/<current_login>/<current_id>', test_views.single_test),  # Конкретный тест
    path('account/reset_answers', account_views.reset_answers), # Очистить ответы пользователя
    path('auth/login/', auth_views.login),  # Страница авторизации
    path('auth/logout/', auth_views.logout),  # Выход из авторизации
    path('auth/registration/', auth_views.registration),  # Регистрация
    path('account/', account_views.personal_account),  # Вход в личный кабинет
    path('account/personal_tests/', account_views.personal_tests),
    path('account/changedata/', account_views.change_profile_data),  # Изменение данных профиля
    path('contact/',pages_views.contact_us),  # Контактная форма
    path('results/<current_login>/<current_test_id>', test_views.test_results),
    path('final_results/<current_login>/<current_test_id>', test_views.final_result),
    path('activate_user/<current_login>/<activation_salt>', account_views.activate_user),
    path('', pages_views.home_page),  # Только адрес сервера - на стартовую страницу
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginSys/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# Create your models here.


class RegistrationForm(UserCreationForm):  # Переопределение формы регистрации
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email",)

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Формат номера: '+79999999999'. До 15 цифр.")

    # Атрибуты
    email = models.EmailField()
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    # Функции
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class ProfessionalRegistrationForm(RegistrationForm):
    def __init__(self, *args, **kwargs):
        super(ProfessionalRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['username'].widget.attrs['class'] = 'text'
        self.fields['username'].widget.attrs['placeholder'] = 'Введите логин'
        self.fields['password1'].help_text = ''
        self.fields['password1'].widget.attrs['class'] = 'text'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].help_text = ''
        self.fields['password2'].widget.attrs['class'] = 'text'
        self.fields['password2'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['email'].help_text = ''
        self.fields['email'].widget.attrs['class'] = 'text'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите email'
        self.fields['email'].required = 'required'

Pages/views.py
from django.shortcuts import render_to_response, redirect
from django.template.context_processors import csrf
from django.contrib import auth
from Profession import settings
from django import forms
from django.http import HttpResponse
from django.core.mail import BadHeaderError
from django.core.mail import EmailMessage

# Create your views here.


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    sender = forms.EmailField()
    message = forms.CharField()
    copy = forms.BooleanField(required=False)


def home_page(request):
    return render_to_response('HomeExtension.html', {'username': auth.get_user(request).username})


def about_project_page(request):
    return render_to_response('AboutProject.html')


def contact_us(request):
    args = {}
    args.update({"email": auth.get_user(request).email})
    args.update(csrf(request))
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recipients = ["barkovgb@yandex.ru"]  # Адрес, на который приходит почта от пользователей сайта

            if copy:
                recipients.append(sender)
            try:
                msg = EmailMessage(subject, message,
                                   from_email=settings.EMAIL_HOST_USER,
                                   to=recipients,
                                   headers={'From': auth.get_user(request).email})
                msg.content_subtype = 'html'
                msg.send(fail_silently=True)
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return redirect("/")
    else:
        return render_to_response('ExtensionContactForm.html', args)

Pages/templates/AboutProject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AboutProject</title>
</head>
<body>
I TRY
</body>
</html>

Pages/templates/ContactForm.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "CSS/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "CSS/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "CSS/styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "CSS/BeautyForm.css" %}">
    <script src="{% static "JS/bootstrap.min.js" %} "></script>
    <script src="{% static "JS/jquery.min.js" %} "></script>
    <title>Title</title>
</head>
<body>

{% block MENU %}
{% endblock %}

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h2 class="contact_header">Форма обратной связи</h2>
            {% block CONTACT_FORM %}
            {% endblock %}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>


</body>
</html>

Pages/templates/ExtensionContactForm.html
{% extends "ContactForm.html" %}

{% block CONTACT_FORM2 %}

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12">
                <form class="form" role="form" method="POST" action="/contact/">
                    {% csrf_token %}
                       <div class="row">
                           <!-- Тема -->
                            <div class="form-group col-sm-6">
                                <label for="id_subject" class="h4">Тема</label>
                                <input type="text" class="form-control" id="id_subject" name="subject" placeholder="Тема" required>
                            </div>
                            <!-- Email -->
                            <div class="form-group col-sm-6">
                                <label for="id_email" class="h4">Email</label>
                                <input type="email" class="form-control" id="id_email" name="sender" value="{{ email }}" required readonly>
                            </div>
                       </div>
                        <div class="form-group">
                            <label for="message" class="h4">Сообщение</label>
                            <textarea id="message" class="form-control" rows="5" placeholder="Введите своё сообщение" name="message" required></textarea>
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="copy" id="id_copy" />
                                <label for="id_copy" class="h4">
                                    Отправить копию себе
                                </label>
                        </div>
                        <button type="submit" id="form-submit" class="btn btn-lg pull-right ">Отправить</button>
                       <!-- <div id="msgSubmit" class="h3 text-center hidden">Message Submitted!</div> -->

                </form>
            </div>
        </div>
    </div>
{%  endblock %}



{% block CONTACT_FORM %}
    <div type="fields">
    <form action="/contact/" method="post">
        {% csrf_token %}
         <label for="id_subject">Тема</label>
         <input type="text" id="id_subject" name="subject" placeholder="Тема.." required>

         <label for="id_email">Email</label>
         <input class="text" type="email" id="id_email" name="sender" value="{{ email }}"  placeholder="Email.." required readonly>

         <label for="message">Сообщение</label>
         <textarea class="text" id="message" rows="5" placeholder="Введите своё сообщение.." name="message" required></textarea>

         <label for="id_copy">Отправить копию себе</label>
         <input type="checkbox" name="copy" id="id_copy" />

         <input type="submit" value="Отправить">
    </form>
    </div>
{% endblock %}





{% block MENU %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav"> <!-- Контент меню -->
            <li class="nav-item">
                    <a class="nav-link" href="/home/"> Главная страница </a>
            </li>
            <li class="nav-item auth_pare">
                <a class="nav-link" href="/account/"> Личный кабинет </a>
            </li>
        </ul>
      </div>
    </nav>
{% endblock %}